apiVersion: platform.example.org/v1alpha1
kind: RedisInstance
metadata:
  name: demo-redis
  namespace: demo
spec:
  compositionRef:
    name: oci-redisinstance

  writeConnectionSecretToRef:
    name: demo-redis-connection

  parameters:
    displayName: demo-redis
    compartmentId: ocid1.compartment.oc1..aaaaaaaayevnkjfyjb6nglndfrvgoy7hciclgf4kq7ioulokey7xfpixjhxa
    subnetId: ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaahwjd57to4sdamx4tjkz2fxwymxdivb5zk6pfuwkiauvscgf5ywdq
    nodeCount: 1
    nodeMemoryInGbs: 2
    softwareVersion: REDIS_7_0