apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: platform

  source:
    repoURL: oci://docker.io/envoyproxy
    chart: gateway-helm
    targetRevision: v1.8.0
    helm:
      releaseName: eg
      values: |
        deployment:
          envoyGateway:
            nodeSelector:
              oke.oraclecloud.com/pool.name: karpenter
            tolerations:
              - key: CriticalAddonsOnly
                operator: Exists
                effect: NoSchedule

  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true