# ---
# apiVersion: karpenter.sh/v1
# kind: NodePool
# metadata:
#   name: spot
# spec:
#   template:
#     spec:
#       taints:
#         - key: oci.oraclecloud.com/oke-is-preemptible
#           value: "true"
#           effect: NoSchedule
#       nodeClassRef:
#         group: oci.oraclecloud.com
#         kind: OCINodeClass
#         name: class1
#       requirements:
#         - key: "karpenter.sh/capacity-type"
#           operator: In
#           values: ["spot"]
#         - key: "oci.oraclecloud.com/instance-shape"
#           operator: In
#           values:
#             - VM.Standard.E5.Flex
#             - VM.Standard.E6.Flex
#         - key: "kubernetes.io/arch"
#           operator: In
#           values: ["amd64"]
#       terminationGracePeriod: 120m
#   disruption:
#     consolidationPolicy: WhenEmpty
#     consolidateAfter: 60m
#     budgets:
#       - nodes: 5%
#   limits:
#     cpu: 64
#     memory: 256Gi
#   weight: 100

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: pool1
spec:
  template:
    spec:
      nodeClassRef:
        group: oci.oraclecloud.com
        kind: OCINodeClass
        name: class1
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "oci.oraclecloud.com/instance-shape"
          operator: In
          values:
            - VM.Standard.E3.Flex
            - VM.Standard.E4.Flex
            - VM.Standard.E5.Flex
            - VM.Standard.E6.Flex
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]

      # Shorter for test cleanup.
      terminationGracePeriod: 5m

  disruption:
    # Test pool: remove empty nodes quickly.
    consolidationPolicy: WhenEmpty
    consolidateAfter: 1m

    # Allow more aggressive cleanup in test.
    budgets:
      - nodes: 50%

  # Raise this based on expected test size.
  # Example: 100 x 2-OCPU nodes = 200 CPU.
  # Example: 100 x 4-OCPU nodes = 400 CPU.
  limits:
    cpu: 20
    memory: 100Gi
---
apiVersion: oci.oraclecloud.com/v1beta1
kind: OCINodeClass
metadata:
  name: class1
spec:
  nodeCompartmentId: "ocid1.compartment.oc1..aaaaaaaayevnkjfyjb6nglndfrvgoy7hciclgf4kq7ioulokey7xfpixjhxa"
  shapeConfigs:
    - ocpus: 1
      memoryInGbs: 4
    - ocpus: 2
      memoryInGbs: 8
    - ocpus: 4
      memoryInGbs: 16
  volumeConfig:
    bootVolumeConfig:
       imageConfig:
        imageType: OKEImage
        imageFilter:
          osFilter: "Oracle Linux"
          osVersionFilter: "8"  # see OCINodeClass docs for imageFilter behavior
  networkConfig:
    primaryVnicConfig:
      networkSecurityGroupConfigs:
        - networkSecurityGroupId: ocid1.networksecuritygroup.oc1.me-jeddah-1.aaaaaaaai5jabx5euzwwepgk47r2atgd2oq6e3dpq3j4rlqqobhgp64nd3ia
      subnetConfig:
        subnetId: ocid1.subnet.oc1.me-jeddah-1.aaaaaaaanathuwpw4k2sfgqenqrbtrox3zfiizsj27agbhb76oa5oym4q2ca
    secondaryVnicConfigs:
      - networkSecurityGroupConfigs:
          - networkSecurityGroupId: ocid1.networksecuritygroup.oc1.me-jeddah-1.aaaaaaaaesnmxjuenvx25sigeohgoa7ynkamvipfvdsdtkphduo5juupsj6q
        subnetConfig:
          subnetId: ocid1.subnet.oc1.me-jeddah-1.aaaaaaaakan35tyrq3ahxxgvg4tbf5tizi2d6tuetmdrqkl6a6ptfj7goyhq
        ipCount: 32