apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workshop
  namespace: argocd
spec:
  description: Instructor-owned OKE workshop labs
  sourceRepos:
    - https://github.com/ronsevetoci/gitops-demo.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: workshop-envoy
    - server: https://kubernetes.default.svc
      namespace: envoy-gateway-system
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: gateway.networking.k8s.io
      kind: GatewayClass
