apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  source:
    repoURL: https://github.com/ronsevetoci/gitops-demo.git
    targetRevision: main
    path: apps/infra/karpenter
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # - CreateNamespace=true
      # IAM resources are often CRDs; this avoids early dry-run failures:
      - SkipDryRunOnMissingResource=true
