---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-provider-oci
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"

---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: oci-workload-identity-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          serviceAccountName: crossplane-provider-oci
          nodeSelector:
            oke.oraclecloud.com/pool.name: karpenter
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
              effect: NoSchedule
          containers:
            - name: package-runtime
              env:
                - name: OCI_RESOURCE_PRINCIPAL_VERSION
                  value: "2.2"
                - name: OCI_RESOURCE_PRINCIPAL_REGION
                  value: "eu-frankfurt-1"
                - name: OCI_RESOURCE_PRINCIPAL_WORKLOAD_IDENTITY
                  value: "1"

---
apiVersion: v1
kind: Secret
metadata:
  name: oci-creds
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  credentials: |
    {
      "auth": "OKEWorkloadIdentity",
      "region": "eu-frankfurt-1"
    }

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: oracle-provider-family-oci
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  package: ghcr.io/oracle/provider-family-oci:<PROVIDER_VERSION>
  runtimeConfigRef:
    name: oci-workload-identity-runtime

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-objectstorage
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  package: ghcr.io/oracle/provider-oci-objectstorage:<PROVIDER_VERSION>
  runtimeConfigRef:
    name: oci-workload-identity-runtime

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-containerengine
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  package: ghcr.io/oracle/provider-oci-containerengine:<PROVIDER_VERSION>
  runtimeConfigRef:
    name: oci-workload-identity-runtime

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-core
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  package: ghcr.io/oracle/provider-oci-core:<PROVIDER_VERSION>
  runtimeConfigRef:
    name: oci-workload-identity-runtime

---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-oci-identity
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  package: ghcr.io/oracle/provider-oci-identity:<PROVIDER_VERSION>
  runtimeConfigRef:
    name: oci-workload-identity-runtime

---
apiVersion: oci.m.upbound.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  credentials:
    source: Secret
    secretRef:
      name: oci-creds
      namespace: crossplane-system
      key: credentials

---
apiVersion: oci.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  credentials:
    source: Secret
    secretRef:
      name: oci-creds
      namespace: crossplane-system
      key: credentials