apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: providers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  project: platform
  source:
    repoURL: https://github.com/ronsevetoci/gitops-demo.git
    targetRevision: master
    path: manifests/crossplane/providers
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - SkipDryRunOnMissingResource=true