apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: oci-redisinstance
  labels:
    provider: oci
    service: redis
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: XRedisInstance

  mode: Pipeline

  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: redis-cluster
            base:
              apiVersion: redis.oci.m.upbound.io/v1alpha1
              kind: RedisCluster
              metadata:
                namespace: crossplane-system
              spec:
                forProvider:
                  compartmentId: ""
                  displayName: ""
                  nodeCount: 1
                  nodeMemoryInGbs: 2
                  softwareVersion: REDIS_7_0
                  subnetId: ""
                providerConfigRef:
                  name: default
                  kind: ClusterProviderConfig

            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.compartmentId
                toFieldPath: spec.forProvider.compartmentId

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.subnetId
                toFieldPath: spec.forProvider.subnetId

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.displayName
                toFieldPath: spec.forProvider.displayName

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.nodeCount
                toFieldPath: spec.forProvider.nodeCount

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.nodeMemoryInGbs
                toFieldPath: spec.forProvider.nodeMemoryInGbs

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.softwareVersion
                toFieldPath: spec.forProvider.softwareVersion

              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.primaryFqdn
                toFieldPath: status.primaryFqdn
                policy:
                  fromFieldPath: Optional

              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.primaryEndpointIpAddress
                toFieldPath: status.primaryEndpointIpAddress
                policy:
                  fromFieldPath: Optional
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.nsgIds
                toFieldPath: spec.forProvider.nsgIds

          - name: redis-connection-configmap
            base:
              apiVersion: kubernetes.m.crossplane.io/v1alpha1
              kind: Object
              metadata:
                namespace: crossplane-system
              spec:
                providerConfigRef:
                  name: in-cluster
                  kind: ClusterProviderConfig
                forProvider:
                  manifest:
                    apiVersion: v1
                    kind: ConfigMap
                    metadata:
                      name: ""
                      namespace: ""
                    data:
                      REDIS_HOST: ""
                      REDIS_PORT: "6379"
                      REDIS_URL: ""

            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.connectionConfigMapName
                toFieldPath: spec.forProvider.manifest.metadata.name

              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.connectionConfigMapNamespace
                toFieldPath: spec.forProvider.manifest.metadata.namespace

              - type: FromCompositeFieldPath
                fromFieldPath: status.primaryFqdn
                toFieldPath: spec.forProvider.manifest.data.REDIS_HOST
                policy:
                  fromFieldPath: Optional

              - type: FromCompositeFieldPath
                fromFieldPath: status.primaryFqdn
                toFieldPath: spec.forProvider.manifest.data.REDIS_URL
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "redis://%s:6379"
                policy:
                  fromFieldPath: Optional