apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: oci-redisinstance
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: XRedisInstance

  mode: Resources

  resources:
    - name: redis-cluster
      base:
        apiVersion: redis.oci.m.upbound.io/v1alpha1
        kind: RedisCluster
        metadata:
          namespace: crossplane-system
        spec:
          forProvider:
            compartmentId: ""
            displayName: ""
            nodeCount: 1
            nodeMemoryInGbs: 2
            softwareVersion: REDIS_7_0
            subnetId: ""
          providerConfigRef:
            name: default
            kind: ProviderConfig